plugins {
    id 'com.android.application'
}

android {
    namespace 'com.winogradsky.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.winogradskiyinstitute.app"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file('winogradsky-release.jks')
            storePassword 'Winogradsky2026!'
            keyAlias 'winogradsky'
            keyPassword 'Winogradsky2026!'
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.biometric:biometric:1.1.0'
}
